name: Sync EssilorLuxottica Brands (Ultra-Fast)

on:
  schedule:
    - cron: '0 6 * * *'  # Ogni giorno alle 6:00 AM UTC
  workflow_dispatch:      # Permette esecuzione manuale
  push:
    branches: [ main ]    # Esegui anche quando pushes su main

jobs:
  sync-brands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # NIENTE npm install! Puppeteer è già nel repository
    - name: Verify Puppeteer (pre-installed)
      run: |
        echo "🔍 Verificando Puppeteer pre-installato..."
        ls -la node_modules/puppeteer/ || echo "❌ Puppeteer non trovato"
        node -e "console.log('✅ Puppeteer version:', require('./node_modules/puppeteer/package.json').version)"
        
    - name: Run brand scraping (LIGHTNING FAST!)
      run: node scrape-brands.js
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add brands.json brands.html
        if git diff --staged --quiet; then
          echo "✅ No changes to commit"
        else
          git commit -m "🔄 Update brands data $(date '+%Y-%m-%d %H:%M')"
          git push
        fi
